/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package P0024_Tictactoe_150;

import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Thanh Vi
 */
public class Cilent_Tictactoe extends javax.swing.JFrame implements Runnable{

      Socket mngSocket=null;
      String mngIP="";
      JList<String>display ;
      int mngPort=0;
      String Name="";
      String receiver="";
      String name=null;
      Vector<Socket> abc;
      Vector<String> listName = new Vector();
      DefaultListModel<String> model = new DefaultListModel<>();
      Thread t;
      BufferedWriter os=null;
      BufferedReader bf=null;
      int SelectedRow=0;
      boolean Xplayer = true;
      int [][] matrix = new int[3][3];
      boolean enable = true;
      int mypos = 0;
       int myposW = 0;
       int SelectedRowW=0;
      boolean playing = false;
      
      public Cilent_Tictactoe() {
            initComponents();
            jPanel18.setBackground(Color.yellow);
            this.setSize(412,193);
            for (int i = 0; i < 3; i++) {
                  for (int j = 0; j < 3; j++) {
                        matrix[i][j]=0;
                  }
            }
            
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanel2 = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jPanel1 = new javax.swing.JPanel();
            lbname = new javax.swing.JLabel();
            tfName = new javax.swing.JTextField();
            StartGame = new javax.swing.JButton();
            jScrollPane1 = new javax.swing.JScrollPane();
            jList1 = new javax.swing.JList<>();
            Invite = new javax.swing.JButton();
            jPanel3 = new javax.swing.JPanel();
            jPanel4 = new javax.swing.JPanel();
            lbSend = new javax.swing.JLabel();
            jPanel7 = new javax.swing.JPanel();
            jLabel12 = new javax.swing.JLabel();
            jPanel6 = new javax.swing.JPanel();
            lbRei = new javax.swing.JLabel();
            jPanel8 = new javax.swing.JPanel();
            jLabel13 = new javax.swing.JLabel();
            jPanel5 = new javax.swing.JPanel();
            jPanel9 = new javax.swing.JPanel();
            g1 = new javax.swing.JLabel();
            jPanel10 = new javax.swing.JPanel();
            g2 = new javax.swing.JLabel();
            jPanel11 = new javax.swing.JPanel();
            g3 = new javax.swing.JLabel();
            jPanel12 = new javax.swing.JPanel();
            g4 = new javax.swing.JLabel();
            jPanel13 = new javax.swing.JPanel();
            g5 = new javax.swing.JLabel();
            jPanel14 = new javax.swing.JPanel();
            g6 = new javax.swing.JLabel();
            jPanel15 = new javax.swing.JPanel();
            g7 = new javax.swing.JLabel();
            jPanel16 = new javax.swing.JPanel();
            g8 = new javax.swing.JLabel();
            jPanel17 = new javax.swing.JPanel();
            g9 = new javax.swing.JLabel();
            jPanel18 = new javax.swing.JPanel();
            nofication = new javax.swing.JLabel();
            exit = new javax.swing.JButton();
            jPanel19 = new javax.swing.JPanel();
            jPanel21 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            yesWin = new javax.swing.JButton();
            noWin = new javax.swing.JButton();
            jPanel20 = new javax.swing.JPanel();
            jPanel22 = new javax.swing.JPanel();
            jPanel23 = new javax.swing.JPanel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            yesLose = new javax.swing.JButton();
            noLose = new javax.swing.JButton();
            jPanel24 = new javax.swing.JPanel();
            jPanel25 = new javax.swing.JPanel();
            jLabel8 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();
            YesOut = new javax.swing.JButton();
            noOut = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            getContentPane().setLayout(new java.awt.CardLayout());

            jPanel2.setBackground(new java.awt.Color(255, 204, 204));

            jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
            jLabel2.setText("Tic-Tac-Toe");

            jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\x455.png")); // NOI18N
            jLabel3.setText("jLabel3");
            jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jLabel3MouseClicked(evt);
                  }
            });

            jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\o455.png")); // NOI18N
            jLabel4.setText("jLabel3");
            jLabel4.setPreferredSize(new java.awt.Dimension(45, 45));

            jPanel1.setBackground(new java.awt.Color(255, 204, 204));
            jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            lbname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            lbname.setText("Name:");

            tfName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

            StartGame.setBackground(new java.awt.Color(255, 153, 153));
            StartGame.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            StartGame.setText("Start game!");
            StartGame.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        StartGameActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StartGame)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(lbname)
                              .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(StartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE))
            );

            jList1.setBackground(new java.awt.Color(255, 204, 204));
            jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            jList1.setSelectionBackground(new java.awt.Color(255, 153, 153));
            jList1.setSelectionForeground(new java.awt.Color(0, 0, 0));
            jScrollPane1.setViewportView(jList1);

            Invite.setBackground(new java.awt.Color(255, 153, 153));
            Invite.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            Invite.setText("Invite");
            Invite.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        InviteActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                  jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                              .addComponent(Invite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                  jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Invite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            getContentPane().add(jPanel2, "Start");

            jPanel3.setBackground(new java.awt.Color(255, 255, 255));

            jPanel4.setBackground(new java.awt.Color(255, 102, 102));
            jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            jPanel4.setForeground(new java.awt.Color(255, 102, 102));
            jPanel4.setPreferredSize(new java.awt.Dimension(185, 77));

            lbSend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            lbSend.setText("User1");

            jPanel7.setBackground(new java.awt.Color(255, 255, 255));
            jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel7.setPreferredSize(new java.awt.Dimension(90, 90));

            jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\x455.png")); // NOI18N
            jLabel12.setText("jLabel1");

            javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
            jPanel7.setLayout(jPanel7Layout);
            jPanel7Layout.setHorizontalGroup(
                  jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
            );
            jPanel7Layout.setVerticalGroup(
                  jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
            );

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                  jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
            );
            jPanel4Layout.setVerticalGroup(
                  jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(lbSend)))
                        .addGap(8, 8, 8))
            );

            jPanel6.setBackground(new java.awt.Color(51, 204, 255));
            jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            jPanel6.setPreferredSize(new java.awt.Dimension(185, 85));

            lbRei.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            lbRei.setText("User2");

            jPanel8.setBackground(new java.awt.Color(255, 255, 255));
            jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel8.setPreferredSize(new java.awt.Dimension(90, 90));

            jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\o455.png")); // NOI18N
            jLabel13.setText("jLabel1");

            javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
            jPanel8.setLayout(jPanel8Layout);
            jPanel8Layout.setHorizontalGroup(
                  jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
            );
            jPanel8Layout.setVerticalGroup(
                  jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
            );

            javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
            jPanel6.setLayout(jPanel6Layout);
            jPanel6Layout.setHorizontalGroup(
                  jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbRei)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
            );
            jPanel6Layout.setVerticalGroup(
                  jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addContainerGap())
                  .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbRei)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jPanel5.setBackground(new java.awt.Color(255, 204, 204));
            jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jPanel9.setBackground(new java.awt.Color(255, 255, 255));
            jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel9.setPreferredSize(new java.awt.Dimension(90, 90));

            g1.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        g1MouseClicked(evt);
                  }
            });

            javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
            jPanel9.setLayout(jPanel9Layout);
            jPanel9Layout.setHorizontalGroup(
                  jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 88, Short.MAX_VALUE)
                  .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE)))
            );
            jPanel9Layout.setVerticalGroup(
                  jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 88, Short.MAX_VALUE)
                  .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE)))
            );

            jPanel10.setBackground(new java.awt.Color(255, 255, 255));
            jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel10.setPreferredSize(new java.awt.Dimension(90, 90));

            g2.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        g2MouseClicked(evt);
                  }
            });

            javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
            jPanel10.setLayout(jPanel10Layout);
            jPanel10Layout.setHorizontalGroup(
                  jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 88, Short.MAX_VALUE)
                  .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE)))
            );
            jPanel10Layout.setVerticalGroup(
                  jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 88, Short.MAX_VALUE)
                  .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE)))
            );

            jPanel11.setBackground(new java.awt.Color(255, 255, 255));
            jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel11.setPreferredSize(new java.awt.Dimension(90, 90));

            g3.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        g3MouseClicked(evt);
                  }
            });

            javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
            jPanel11.setLayout(jPanel11Layout);
            jPanel11Layout.setHorizontalGroup(
                  jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
            );
            jPanel11Layout.setVerticalGroup(
                  jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
            );

            jPanel12.setBackground(new java.awt.Color(255, 255, 255));
            jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel12.setPreferredSize(new java.awt.Dimension(90, 90));

            g4.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        g4MouseClicked(evt);
                  }
            });

            javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
            jPanel12.setLayout(jPanel12Layout);
            jPanel12Layout.setHorizontalGroup(
                  jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 88, Short.MAX_VALUE)
                  .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE)))
            );
            jPanel12Layout.setVerticalGroup(
                  jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 88, Short.MAX_VALUE)
                  .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE)))
            );

            jPanel13.setBackground(new java.awt.Color(255, 255, 255));
            jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel13.setPreferredSize(new java.awt.Dimension(90, 90));

            g5.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        g5MouseClicked(evt);
                  }
            });

            javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
            jPanel13.setLayout(jPanel13Layout);
            jPanel13Layout.setHorizontalGroup(
                  jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 88, Short.MAX_VALUE)
                  .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE)))
            );
            jPanel13Layout.setVerticalGroup(
                  jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 88, Short.MAX_VALUE)
                  .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE)))
            );

            jPanel14.setBackground(new java.awt.Color(255, 255, 255));
            jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel14.setPreferredSize(new java.awt.Dimension(90, 90));

            g6.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        g6MouseClicked(evt);
                  }
            });

            javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
            jPanel14.setLayout(jPanel14Layout);
            jPanel14Layout.setHorizontalGroup(
                  jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(g6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
            );
            jPanel14Layout.setVerticalGroup(
                  jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(g6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
            );

            jPanel15.setBackground(new java.awt.Color(255, 255, 255));
            jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel15.setPreferredSize(new java.awt.Dimension(90, 90));
            jPanel15.setRequestFocusEnabled(false);

            g7.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        g7MouseClicked(evt);
                  }
            });

            javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
            jPanel15.setLayout(jPanel15Layout);
            jPanel15Layout.setHorizontalGroup(
                  jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(g7, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
            );
            jPanel15Layout.setVerticalGroup(
                  jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(g7, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
            );

            jPanel16.setBackground(new java.awt.Color(255, 255, 255));
            jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel16.setPreferredSize(new java.awt.Dimension(90, 90));

            g8.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        g8MouseClicked(evt);
                  }
            });

            javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
            jPanel16.setLayout(jPanel16Layout);
            jPanel16Layout.setHorizontalGroup(
                  jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(g8, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
            );
            jPanel16Layout.setVerticalGroup(
                  jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(g8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jPanel17.setBackground(new java.awt.Color(255, 255, 255));
            jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel17.setPreferredSize(new java.awt.Dimension(90, 90));

            g9.setAlignmentX(4.0F);
            g9.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        g9MouseClicked(evt);
                  }
            });

            javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
            jPanel17.setLayout(jPanel17Layout);
            jPanel17Layout.setHorizontalGroup(
                  jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(g9, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
            );
            jPanel17Layout.setVerticalGroup(
                  jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(g9, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
            );

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                  jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7)
                                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7)
                                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7)
                                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7)
                                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel5Layout.setVerticalGroup(
                  jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
            );

            jPanel18.setBackground(new java.awt.Color(255, 255, 255));
            jPanel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            nofication.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            nofication.setText("....");

            javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
            jPanel18.setLayout(jPanel18Layout);
            jPanel18Layout.setHorizontalGroup(
                  jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel18Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nofication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );
            jPanel18Layout.setVerticalGroup(
                  jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(nofication)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            exit.setBackground(new java.awt.Color(255, 255, 255));
            exit.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\cross.png")); // NOI18N
            exit.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        exitActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                  jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))
            );
            jPanel3Layout.setVerticalGroup(
                  jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                              .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
            );

            getContentPane().add(jPanel3, "tictactoe");

            jPanel19.setBackground(new java.awt.Color(255, 102, 102));

            jPanel21.setBackground(new java.awt.Color(255, 255, 255));
            jPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jLabel1.setBackground(new java.awt.Color(255, 102, 102));
            jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 51, 51));
            jLabel1.setText("You Win!");

            jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            jLabel5.setText("Do you want to play again??");

            yesWin.setBackground(new java.awt.Color(255, 102, 102));
            yesWin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            yesWin.setText("Yes");
            yesWin.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        yesWinActionPerformed(evt);
                  }
            });

            noWin.setBackground(new java.awt.Color(255, 102, 102));
            noWin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            noWin.setText("No");
            noWin.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        noWinActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
            jPanel21.setLayout(jPanel21Layout);
            jPanel21Layout.setHorizontalGroup(
                  jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel21Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(yesWin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(noWin))
                              .addComponent(jLabel5)
                              .addComponent(jLabel1))
                        .addContainerGap(85, Short.MAX_VALUE))
            );
            jPanel21Layout.setVerticalGroup(
                  jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(yesWin)
                              .addComponent(noWin))
                        .addContainerGap(164, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
            jPanel19.setLayout(jPanel19Layout);
            jPanel19Layout.setHorizontalGroup(
                  jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel19Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );
            jPanel19Layout.setVerticalGroup(
                  jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel19Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );

            getContentPane().add(jPanel19, "Win");

            jPanel22.setBackground(new java.awt.Color(0, 204, 204));

            jPanel23.setBackground(new java.awt.Color(255, 255, 255));
            jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(0, 153, 153));
            jLabel6.setText("You Lose!");

            jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            jLabel7.setText("Do you want to play again??");

            yesLose.setBackground(new java.awt.Color(0, 204, 204));
            yesLose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            yesLose.setText("Yes");
            yesLose.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        yesLoseActionPerformed(evt);
                  }
            });

            noLose.setBackground(new java.awt.Color(0, 204, 204));
            noLose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            noLose.setText("No");
            noLose.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        noLoseActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
            jPanel23.setLayout(jPanel23Layout);
            jPanel23Layout.setHorizontalGroup(
                  jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel23Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(yesLose)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(noLose))
                              .addComponent(jLabel7)
                              .addComponent(jLabel6))
                        .addContainerGap(69, Short.MAX_VALUE))
            );
            jPanel23Layout.setVerticalGroup(
                  jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(yesLose)
                              .addComponent(noLose))
                        .addContainerGap(158, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
            jPanel22.setLayout(jPanel22Layout);
            jPanel22Layout.setHorizontalGroup(
                  jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );
            jPanel22Layout.setVerticalGroup(
                  jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );

            javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
            jPanel20.setLayout(jPanel20Layout);
            jPanel20Layout.setHorizontalGroup(
                  jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 420, Short.MAX_VALUE)
                  .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel20Layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE)))
            );
            jPanel20Layout.setVerticalGroup(
                  jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 497, Short.MAX_VALUE)
                  .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel20Layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE)))
            );

            getContentPane().add(jPanel20, "Lose");

            jPanel24.setBackground(new java.awt.Color(255, 153, 204));

            jPanel25.setBackground(new java.awt.Color(255, 255, 255));
            jPanel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jLabel8.setBackground(new java.awt.Color(255, 51, 204));
            jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
            jLabel8.setForeground(new java.awt.Color(255, 51, 153));
            jLabel8.setText("Out Of Move!");

            jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            jLabel9.setText("Do you want to play again??");

            YesOut.setBackground(new java.awt.Color(255, 102, 204));
            YesOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            YesOut.setText("Yes");
            YesOut.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        YesOutActionPerformed(evt);
                  }
            });

            noOut.setBackground(new java.awt.Color(255, 102, 204));
            noOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            noOut.setText("No");
            noOut.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        noOutActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
            jPanel25.setLayout(jPanel25Layout);
            jPanel25Layout.setHorizontalGroup(
                  jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel25Layout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addGroup(jPanel25Layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(YesOut)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(noOut))
                                          .addComponent(jLabel9)))
                              .addGroup(jPanel25Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jLabel8)))
                        .addContainerGap(35, Short.MAX_VALUE))
            );
            jPanel25Layout.setVerticalGroup(
                  jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(YesOut)
                              .addComponent(noOut))
                        .addContainerGap(164, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
            jPanel24.setLayout(jPanel24Layout);
            jPanel24Layout.setHorizontalGroup(
                  jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel24Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
            );
            jPanel24Layout.setVerticalGroup(
                  jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel24Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
            );

            getContentPane().add(jPanel24, "outofmove");

            pack();
      }// </editor-fold>//GEN-END:initComponents

      public void resetgame(){
            for (int i = 0; i < 3; i++) {
                  for (int j = 0; j < 3; j++) {
                        matrix[i][j]=0;
                  }
            }
            g1.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\white.png"));
            g2.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\white.png"));
            g3.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\white.png"));
            g4.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\white.png"));
            g5.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\white.png"));
            g6.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\white.png"));
            g7.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\white.png"));
            g8.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\white.png"));
            g9.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\white.png"));
}
      
      private void StartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameActionPerformed
            mngIP = "localhost";//get server and server port
            mngPort = 8888;
            Name=this.tfName.getText();
            if (Name.length()<=0) {
                  JOptionPane.showMessageDialog(this,"Please enter your name!");
                  lbname.requestFocus();
                  return;
            }
            try {
                  mngSocket=new Socket(mngIP,mngPort); //connect to server
                  if(mngSocket!=null){
                        this.setSize(412,535);
                        Server_Tictactoe sv = new Server_Tictactoe();
                        t = new Thread(this);
                        t.start();
                        bf=new BufferedReader(new InputStreamReader(mngSocket.getInputStream()));
                        os=new BufferedWriter(new OutputStreamWriter(mngSocket.getOutputStream()));
                        os.write("User: " + Name);
                        os.newLine();
                        os.flush();
                  }
            } catch (Exception e) {
                  JOptionPane.showMessageDialog(this, "Manager is not running.");
                  System.exit(0);
            }
            StartGame.setEnabled(false);
      }//GEN-LAST:event_StartGameActionPerformed

      private void InviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InviteActionPerformed

            SelectedRow = jList1.getSelectedIndex();
            for (int i = 0; i <model.size(); i++) {
                  if(model.get(i).contains("(Me)")){
                        mypos = i;
                        break;
                  }
                  }
            if(SelectedRow<0){
                  JOptionPane.showMessageDialog(this, "Please choose friend to play!");
                  return;
            }
            if(SelectedRow==mypos){
                  JOptionPane.showMessageDialog(this, "You can not play this game with yourself!");
            }else{
                  int r = JOptionPane.showConfirmDialog(this, "Do you want to play game with '"+ model.get(SelectedRow).substring(2).toString()+ "'' ?", "Invite?", JOptionPane.YES_NO_OPTION);
                             if(r==JOptionPane.YES_OPTION){ 
                                  CheckPlaying();
                                  
                        }
            }    
      }//GEN-LAST:event_InviteActionPerformed

      public void CheckPlaying(){
            String a = "@"+SelectedRow+mypos+Name;
            sendtoServer(a);
      }
      
      private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

            CardLayout CLT=(CardLayout)this.getContentPane().getLayout();
            CLT.show(this.getContentPane(),"b");
      }//GEN-LAST:event_jLabel3MouseClicked

      private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
            int r= JOptionPane.showConfirmDialog(this, "Do you want to leave and lose the game???" , "Exit?", JOptionPane.YES_NO_OPTION);
            if (r == JOptionPane.YES_OPTION) {
            CardLayout CLT=(CardLayout)this.getContentPane().getLayout();
            CLT.show(this.getContentPane(),"Start");
            playing=false;
            sendtoServer("x"+SelectedRow+Name);
            }
      }//GEN-LAST:event_exitActionPerformed

      public boolean checkValidPos(int m,int n){
            boolean valid = true;
            if (matrix[m][n]==0) {
                  valid = true;
            }else{
                  valid = false;
            }
            return valid; 
      }
      
      public void checkWin(int m,int n){
            int value = 0;
            boolean full = true;
            boolean flag = true;
            for (int i = 0; i < 3; i++) {
                  for (int j = 0; j < 3; j++) {
                        if(matrix[i][j]==0){
                              full=false;
                              break;
                        }else{
                              full=true;
                        }
                  }
            }
                  if (Xplayer) {
                        value = 1;
                  } else {
                        value = 2;
                  }
                  if ((matrix[m][0] == value && matrix[m][1] == value && matrix[m][2] == value) || (matrix[0][n] == value && matrix[1][n] == value && matrix[2][n] == value)) {
                        CardLayout CLT = (CardLayout) this.getContentPane().getLayout();
                        CLT.show(this.getContentPane(), "Win");
                        resetgame();
                        sendtoServer("-" + SelectedRow);
                        sendtoServer("."+SelectedRow+mypos);
                        flag=false;
                  } else if ((matrix[0][0] == value && matrix[1][1] == value && matrix[2][2] == value) || (matrix[0][2] == value && matrix[1][1] == value && matrix[2][0] == value)) {
                        CardLayout CLT = (CardLayout) this.getContentPane().getLayout();
                        CLT.show(this.getContentPane(), "Win");
                        resetgame();
                        sendtoServer("-" + SelectedRow);
                        sendtoServer("."+SelectedRow+mypos);
                        flag=false;
                  }
                  if(full==true && flag ==true){
                        CardLayout CLT = (CardLayout) this.getContentPane().getLayout();
                        CLT.show(this.getContentPane(), "outofmove");
                        resetgame();
                        sendtoServer("o" + SelectedRow);
                  }
            
      }
      
      public void clickBox(JLabel g,int m, int n,int value){
            if(checkValidPos(m, n) && enable==true){
                  if (Xplayer) {
                        g.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\x68.png"));
                        matrix[m][n] = 1;
                        sendtoServer("=" + SelectedRow + m + n + value + "x");
                  } else {
                        g.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\o68.png"));
                        matrix[m][n] = 2;
                        sendtoServer("=" + SelectedRow + m + n + value + "o");
                  }
                  nofication.setText("Not your turn!");
                  sendtoServer("("+SelectedRow);
                  disable();
                  checkWin(m, n);
            }else{
                  nofication.setText("You can't check in this box");
            }
      }
      private void g1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g1MouseClicked
            int m, n =0;
            m = 0;  n = 0;
            clickBox(g1,m, n, 1);
      }//GEN-LAST:event_g1MouseClicked

      private void g2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g2MouseClicked
            int m, n =0;
            m = 0;  n = 1;
            clickBox(g2,m, n, 2);
            
      }//GEN-LAST:event_g2MouseClicked

      private void g3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g3MouseClicked
            int m, n =0;
            m = 0;  n = 2;
            clickBox(g3,m, n, 3);
      }//GEN-LAST:event_g3MouseClicked

      private void g4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g4MouseClicked
           int m, n =0;
            m = 1;  n = 0;
            clickBox(g4,m, n, 4);
      }//GEN-LAST:event_g4MouseClicked

      private void g5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g5MouseClicked
            int m, n =0;
            m = 1;  n = 1;
            clickBox(g5,m, n, 5);
      }//GEN-LAST:event_g5MouseClicked

      private void g7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g7MouseClicked
            int m, n =0;
            m = 2;  n = 0;
            clickBox(g7,m, n, 7);
      }//GEN-LAST:event_g7MouseClicked

      private void g8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g8MouseClicked
            int m, n =0;
            m = 2;  n = 1;
            clickBox(g8,m, n, 8);
      }//GEN-LAST:event_g8MouseClicked

      private void g9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g9MouseClicked
            int m, n =0;
            m = 2;  n = 2;
            clickBox(g9,m, n, 9);
      }//GEN-LAST:event_g9MouseClicked

      private void noWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noWinActionPerformed
            No();
      }//GEN-LAST:event_noWinActionPerformed

      private void noLoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noLoseActionPerformed
            No();
      }//GEN-LAST:event_noLoseActionPerformed

      private void g6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_g6MouseClicked
            int m, n =0;
            m = 1;  n = 2;
            clickBox(g6,m, n, 6);
      }//GEN-LAST:event_g6MouseClicked

      private void noOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOutActionPerformed
            No();
      }//GEN-LAST:event_noOutActionPerformed

      private void yesWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesWinActionPerformed
           Yes();
      }//GEN-LAST:event_yesWinActionPerformed

      private void yesLoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesLoseActionPerformed
            Yes();
      }//GEN-LAST:event_yesLoseActionPerformed

      private void YesOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesOutActionPerformed
            Yes();
      }//GEN-LAST:event_YesOutActionPerformed

      public void No(){
            int r= JOptionPane.showConfirmDialog(this, "Do you want to leave the game???" , "Exit?", JOptionPane.YES_NO_OPTION);
            if (r == JOptionPane.YES_OPTION) {
            CardLayout CLT=(CardLayout)this.getContentPane().getLayout();
            CLT.show(this.getContentPane(),"Start");
            playing=false;
            sendtoServer("x"+SelectedRow+Name);
            }
      }
      public void Yes(){
            int r = JOptionPane.showConfirmDialog(this, "Do you want to play game again with?", "Invite?", JOptionPane.YES_NO_OPTION);
            if(r==JOptionPane.YES_OPTION){ 
                       String a = "y"+SelectedRow+mypos;
                        sendtoServer(a);
            }
      }
 
      
      
      public void sendtoServer(String stt){
            try {
                  os.write(stt);
                  os.newLine();
                  os.flush();
            } catch (Exception e) {
                  JOptionPane.showMessageDialog(this, e);
            }
       }

          @Override
            public void run(){
                  while(true)
                        try {
                              if(mngSocket!=null){
                                    String msg="";
                                    if((msg=bf.readLine())!= null && msg.length()>0){   
                                          System.out.println(msg);
                                          switch(msg.charAt(0)){
                                                case '*': 
                                                      check1(msg);
                                                      break;
                                                case '>':
                                                      Invited(msg);
                                                      break;
                                                case '!':
                                                      JOptionPane.showMessageDialog(this,msg.substring(1).toUpperCase()+" deny your request!");
                                                      CardLayout CLT=(CardLayout)this.getContentPane().getLayout();
                                                      CLT.show(this.getContentPane(),"Start");
                                                      playing=false;
                                                      break;
                                                case '#':
                                                      lbSend.setText((Name+"(ME)").toUpperCase());
                                                      lbRei.setText(receiver.toUpperCase());
                                                      CLT=(CardLayout)this.getContentPane().getLayout();
                                                      CLT.show(this.getContentPane(),"tictactoe");
                                                      playing=true;
                                                      Xplayer = true;
                                                      enable = true;
                                                      jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\x455.png")); 
                                                      jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\o455.png")); 
                                                      jPanel6.setBackground(new java.awt.Color(51, 204, 255));
                                                      jPanel4.setBackground(new java.awt.Color(255, 102, 102));
                                                      nofication.setText("Your turn!");
                                                      sendtoServer(")"+SelectedRow);
                                                      break;
                                                  
                                                case 'x':
                                                      JOptionPane.showMessageDialog(this,msg.substring(2).toUpperCase()+" has left the game!");
                                                      CLT=(CardLayout)this.getContentPane().getLayout();
                                                      CLT.show(this.getContentPane(),"Start");
                                                      playing=false;
                                                      break;
                                                case '&':
                                                      model.removeElementAt(Integer.parseInt(msg.substring(1)));
                                                      display.setModel(model);
                                                      break;
                                                case '=':
                                                      int m = Integer.parseInt(msg.substring(2, 3));
                                                      int n = Integer.parseInt(msg.substring(3, 4));
                                                      int index = Integer.parseInt(msg.substring(4, 5));
                                                      String xo = msg.substring(5, 6);
                                                      System.out.println("cilent:"+ Name+xo);
                                                      check(index, m, n,xo);
                                                      break;
                                                 case '-':
                                                       CLT=(CardLayout)this.getContentPane().getLayout();
                                                       CLT.show(this.getContentPane(),"Lose");
                                                       resetgame();
                                                      break;
                                                  case ')':
                                                      nofication.setText("Not your turn!");
                                                      disable();
                                                      break;
                                                 case '(':
                                                      nofication.setText("Your turn!");
                                                      enable();
                                                      break;
                                                 case 'o':
                                                      CLT=(CardLayout)this.getContentPane().getLayout();
                                                       CLT.show(this.getContentPane(),"outofmove");
                                                      break;
                                                 case 'y': 
                                                       if(msg.substring(1,2).equals("y")){
                                                             if (Xplayer) {
                                                                   O(msg);
                                                             } else {
                                                                   X(msg);
                                                             }
                                                       }else{
                                                             int r= JOptionPane.showConfirmDialog(this, "Do you want to play game again?", "Invite?", JOptionPane.YES_NO_OPTION);
                                                             if (r == JOptionPane.YES_OPTION) {
                                                                   if (Xplayer) {
                                                                         O(msg);
                                                                   } else {
                                                                         X(msg);
                                                                   }
                                                             }else{
                                                                   CLT=(CardLayout)this.getContentPane().getLayout();
                                                                  CLT.show(this.getContentPane(),"Start");
                                                                  playing=false;
                                                                   sendtoServer("!"+SelectedRow+Name);
                                                             }     
                                                       }
                                                      break;
                                                case '.': 
                                                       myposW = Integer.parseInt(msg.substring(2, 3));
                                                       SelectedRowW=Integer.parseInt(msg.substring(1, 2));
                                                      break;
                                                case '@': 
                                                       if (playing) {
                                                             sendtoServer("~y"+msg.substring(2,3)+Name);
                                                      }else{
                                                             sendtoServer("~n"+msg.substring(2,3)+Name);
                                                       }
                                                      break; 
                                                 case '~':
                                                      if(msg.substring(1,2).equals("y")){
                                                            JOptionPane.showMessageDialog(this,msg.substring(3).toUpperCase()+" is playing game!");
                                                      }else{
                                                            String a = ">"+SelectedRow+mypos+Name;
                                                            receiver = model.get(SelectedRow).substring(1);
                                                            sendtoServer(a);
                                                      }
                                                      break; 
                                    }
                              }
                              }
                        } catch (Exception e) {
                              e.getMessage();
                        }
            }
   //----------------------------------------------------------------------------------------------------------------------------         
            public void check1(String msg){
            int kt =0;
                for (int i = 0; i < model.size(); i++) {
                      if (!(model.get(i).equals(msg)) && !(model.get(i).equals(msg + " (Me)"))) {
                            kt = 0;
                      } else {
                            kt = 1;
                            break;
                      }
                }
                if (msg.substring(2).equals(Name)) {
                      msg = msg + " (Me)";
                      System.out.println(msg);
                }
                if (kt == 0) {
                      model.addElement(msg);
                      jList1.setModel(model);
                  }
                return;
}
//---------------------------------------------------------------------------------------------------------------------------------
            public void Invited(String mess){
                 receiver = mess.substring(3);
                 int r= JOptionPane.showConfirmDialog(this, "Do you want to play game with '" + mess.substring(3) + "' ?", "Invite?", JOptionPane.YES_NO_OPTION);
                 if (r == JOptionPane.YES_OPTION) {
                              playing=true;
                              sendtoServer("#"+mess.substring(2,3)+Name);
                              SelectedRow=Integer.parseInt(mess.substring(2, 3));
                              mypos=Integer.parseInt(mess.substring(1, 2));
                              lbSend.setText((Name+"(ME)").toUpperCase());
                              lbRei.setText(receiver.toUpperCase());
                              CardLayout CLT=(CardLayout)this.getContentPane().getLayout();
                              CLT.show(this.getContentPane(),"tictactoe");
                              Xplayer=false;
                              jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\o455.png")); 
                              jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\x455.png")); 
                              jPanel4.setBackground(new java.awt.Color(51, 204, 255));
                              jPanel6.setBackground(new java.awt.Color(255, 102, 102));//do
                              enable = false;
                              nofication.setText("Not your turn!");
                 }else{
                              CardLayout CLT=(CardLayout)this.getContentPane().getLayout();
                              CLT.show(this.getContentPane(),"Start");
                              sendtoServer("!"+mess.substring(2,3)+Name);
                              playing=false;
                 }
            }
//---------------------------------------------------------------------------------------------------------------------------------
            public void O(String mess){
                  System.out.println("OOOOOO");
                              resetgame();
                              CardLayout CLT=(CardLayout)this.getContentPane().getLayout();
                              CLT.show(this.getContentPane(),"tictactoe");
                              Xplayer=false;
                              jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\o455.png")); 
                              jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\x455.png")); 
                              jPanel4.setBackground(new java.awt.Color(51, 204, 255));
                              jPanel6.setBackground(new java.awt.Color(255, 102, 102));
                              enable = false;
                              nofication.setText("Not your turn!");
                 
            }
//---------------------------------------------------------------------------------------------------------------------------------
            public void X(String mess){
                  System.out.println("XXXXXXXXXXXXXXX");
                              resetgame();
                              CardLayout CLT=(CardLayout)this.getContentPane().getLayout();
                              CLT.show(this.getContentPane(),"tictactoe");
                              Xplayer=true;
                              jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\x455.png")); 
                              jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\o455.png")); 
                              jPanel6.setBackground(new java.awt.Color(51, 204, 255));
                              jPanel4.setBackground(new java.awt.Color(255, 102, 102));
                              enable = true;
                              nofication.setText("Your turn!");
            }

//-------------------------------------------------------------------------------------------------------------
            public void disable(){
                  enable = false;

            }
//-------------------------------------------------------------------------------------------------------------
            public void enable(){
                  enable = true;  
            }
//-------------------------------------------------------------------------------------------------------------
            public void CheckClick(JLabel g,String xo,int m,int n){
                  if (xo.equals("x")) {
                                     g.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\x68.png"));
                                     matrix[m][n] = 1;
                               } else {
                                     g.setIcon(new javax.swing.ImageIcon("C:\\Java\\TICTACTOE\\o68.png"));
                                     matrix[m][n] = 2;
                               }
            }
//-------------------------------------------------------------------------------------------------------------
            public void check(int index, int m, int n, String xo){
                  switch(index){
                         case 1:
                               CheckClick(g1, xo, m, n);
                              break;
                         case 2:
                              CheckClick(g2, xo, m, n);
                              break;
                         case 3:
                              CheckClick(g3, xo, m, n);
                              break;
                         case 4:
                              CheckClick(g4, xo, m, n);
                              break;
                         case 5:
                              CheckClick(g5, xo, m, n);
                              break;
                         case 6:
                              CheckClick(g6, xo, m, n);
                              break;
                         case 7:
                              CheckClick(g7, xo, m, n);
                              break;
                         case 8:
                              CheckClick(g8, xo, m, n);
                              break;
                         case 9:
                              CheckClick(g9, xo, m, n);
                              break;
                  }
            }

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(Cilent_Tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(Cilent_Tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(Cilent_Tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(Cilent_Tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new Cilent_Tictactoe().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton Invite;
      private javax.swing.JButton StartGame;
      private javax.swing.JButton YesOut;
      private javax.swing.JButton exit;
      private javax.swing.JLabel g1;
      private javax.swing.JLabel g2;
      private javax.swing.JLabel g3;
      private javax.swing.JLabel g4;
      private javax.swing.JLabel g5;
      private javax.swing.JLabel g6;
      private javax.swing.JLabel g7;
      private javax.swing.JLabel g8;
      private javax.swing.JLabel g9;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel12;
      private javax.swing.JLabel jLabel13;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JLabel jLabel7;
      private javax.swing.JLabel jLabel8;
      private javax.swing.JLabel jLabel9;
      private javax.swing.JList<String> jList1;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JPanel jPanel10;
      private javax.swing.JPanel jPanel11;
      private javax.swing.JPanel jPanel12;
      private javax.swing.JPanel jPanel13;
      private javax.swing.JPanel jPanel14;
      private javax.swing.JPanel jPanel15;
      private javax.swing.JPanel jPanel16;
      private javax.swing.JPanel jPanel17;
      private javax.swing.JPanel jPanel18;
      private javax.swing.JPanel jPanel19;
      private javax.swing.JPanel jPanel2;
      private javax.swing.JPanel jPanel20;
      private javax.swing.JPanel jPanel21;
      private javax.swing.JPanel jPanel22;
      private javax.swing.JPanel jPanel23;
      private javax.swing.JPanel jPanel24;
      private javax.swing.JPanel jPanel25;
      private javax.swing.JPanel jPanel3;
      private javax.swing.JPanel jPanel4;
      private javax.swing.JPanel jPanel5;
      private javax.swing.JPanel jPanel6;
      private javax.swing.JPanel jPanel7;
      private javax.swing.JPanel jPanel8;
      private javax.swing.JPanel jPanel9;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JLabel lbRei;
      private javax.swing.JLabel lbSend;
      private javax.swing.JLabel lbname;
      private javax.swing.JButton noLose;
      private javax.swing.JButton noOut;
      private javax.swing.JButton noWin;
      private javax.swing.JLabel nofication;
      private javax.swing.JTextField tfName;
      private javax.swing.JButton yesLose;
      private javax.swing.JButton yesWin;
      // End of variables declaration//GEN-END:variables
}
